package fr.sii.ogham.email.builder;

import fr.sii.ogham.core.builder.AbstractParent;
import fr.sii.ogham.core.builder.Builder;
import fr.sii.ogham.core.id.generator.IdGenerator;
import fr.sii.ogham.email.message.Email;

/**
 * Configures how images are attached to {@link Email}s.
 * 
 * Image defined in a html must be referenced by a
 * <a href="https://tools.ietf.org/html/rfc4021#section-2.2.2">Content-ID (or
 * CID)</a> if the image is attached to the email. You can define how CIDs are
 * generated.
 * 
 * 
 * @author Aurélien Baudet
 *
 */
public class CidBuilder extends AbstractParent<AttachImageBuilder> implements Builder<IdGenerator> {
	private IdGenerator idGenerator;

	/**
	 * Initializes with the parent (used when calling {@link #and()} method for
	 * fluent chaining).
	 * 
	 * @param parent
	 *            the parent builder
	 */
	public CidBuilder(AttachImageBuilder parent) {
		super(parent);
	}

	/**
	 * Image defined in a html must be referenced by a
	 * <a href="https://tools.ietf.org/html/rfc4021#section-2.2.2">Content-ID
	 * (or CID)</a> if the image is attached to the email. You can define how
	 * CIDs are generated by defining an {@link IdGenerator}.
	 * 
	 * @param generator
	 *            the cid generator
	 * @return this instance for fluent chaining
	 */
	public CidBuilder generator(IdGenerator generator) {
		idGenerator = generator;
		return this;
	}

	@Override
	public IdGenerator build() {
		return idGenerator;
	}
}
