:relative-path: ../
include::{docdir}/variables.adoc[]


image:https://img.shields.io/maven-central/v/fr.sii.ogham/ogham-all.svg["Latest Release Standalone", link="https://mvnrepository.com/artifact/fr.sii.ogham/ogham-all/{ogham-version}"]
image:https://img.shields.io/badge/License-Apache%202.0-lightgrey.svg["License", link="https://opensource.org/licenses/Apache-2.0"]
image:https://travis-ci.org/groupe-sii/ogham.svg?branch={badges-branch}["Build Status", link="https://travis-ci.org/groupe-sii/ogham"]

image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=alert_status["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=sqale_rating["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=reliability_rating["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=security_rating["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]

image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=coverage["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=sqale_index["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=bugs["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=vulnerabilities["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]



= Ogham
{ogham-version}

latest release: **v{ogham-version}** {site-version-url}[site] {sourcedir-url}[code]

current development: **v{ogham-dev-version}** {site-dev-version-url}[site] {sourcedir-dev-url}[code] 

Previous versions:
{site-url}/v1.1.1[v1.1.1]
{site-url}/v1.1.0[v1.1.0]
{site-url}/v1.0.0[v1.0.0]
{site-url}/v0.0.1[v0.0.1]


== Introduction

include::{user-manual-dir}/introduction.adoc[leveloffset=+1]

== Quick start

include::{user-manual-dir}/quick-start.adoc[leveloffset=+1]

== Usage

include::{user-manual-dir}/usage.adoc[leveloffset=+1]

== Testing

include::{user-manual-dir}/testing.adoc[leveloffset=+1]

== Advanced configuration

{site-version-url}/user-manual.html#section-advanced-configuration[See advanced configuration in full documentation]

== Extend

{site-version-url}/user-manual.html#section-extend[See how to extend in full documentation]

== Tips

{site-version-url}/user-manual.html#section-tips[See tips in full documentation]

