:relative-path: ../
include::{docdir}/variables.adoc[]


ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


= Ogham
:toc: preamble
:toclevels: 3

image:https://img.shields.io/maven-central/v/fr.sii.ogham/ogham-all.svg["Latest Release Standalone", link="https://mvnrepository.com/artifact/fr.sii.ogham/ogham-all/{ogham-version}"]
image:https://img.shields.io/badge/License-Apache%202.0-lightgrey.svg["License", link="https://opensource.org/licenses/Apache-2.0"]
image:https://travis-ci.org/groupe-sii/ogham.svg?branch={badges-branch}["Build Status", link="https://travis-ci.org/groupe-sii/ogham"]

image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=alert_status["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=sqale_rating["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=reliability_rating["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=security_rating["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]

image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=coverage["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=sqale_index["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=bugs["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.sii.ogham%3Aogham-parent&metric=vulnerabilities["Sonar", link="https://sonarcloud.io/dashboard?id=fr.sii.ogham%3Aogham-parent"]



[%autowidth.stretch]
|===
| Latest release | **v{ogham-version}** | {site-version-url}[site] | {sourcedir-url}[code]
| Current development | **v{ogham-dev-version}** | {site-dev-version-url}[site] | {sourcedir-dev-url}[code]
|=== 



== Introduction

include::{user-manual-dir}/introduction.adoc[leveloffset=+1]

== Quick start

=== Standalone

include::{user-manual-dir}/installation/standalone-all.adoc[leveloffset=+2]

=== With Spring Boot

include::{user-manual-dir}/installation/springboot-all.adoc[leveloffset=+2]

== Select the features you need

Importing `ogham-all` dependency or `ogham-spring-boot-starter-all` dependency 
is easy but may import dependencies that you
don't need. For example, you may only need FreeMarker but not Thymeleaf. Or
you may only need to send emails through SMTP but never use SendGrid.

See how to {site-version-url}/user-manual.html#select-features-standalone[select features].


== Usage


[NOTE]
====
All samples with templates are using ThymeLeaf as template engine. For FreeMarker samples, 
take a look at {site-version-url}/user-manual.html#freemarker[FreeMarker section].
====

=== Send Email

[NOTE]
====
The samples are available in the {standard-samples-url}[sample-standard-usage sub-project].

All samples shown bellow are using SMTP for sending email. 
See {site-version-url}/user-manual.html#sendgrid[Sending email through SendGrid] 
to know how to send email using SendGrid HTTP API.
====

==== First email using an existing SMTP server

include::{user-manual-dir}/email/first-email.adoc[leveloffset=+3]

==== Use an HTML template for email body

include::{user-manual-dir}/email/template-body.adoc[leveloffset=+3]

==== Use HTML title as email subject

include::{user-manual-dir}/email/html-title-subject.adoc[leveloffset=+3]
include::{user-manual-dir}/email/text-first-line-subject.adoc[leveloffset=+3]

==== HTML body with CSS and images

include::{user-manual-dir}/email/css-and-images.adoc[leveloffset=+3]

==== A working preview of the HTML body (text alternative)

include::{user-manual-dir}/email/text-preview.adoc[leveloffset=+3]

==== Attach files to the email

include::{user-manual-dir}/email/attach-files.adoc[leveloffset=+3]

==== Other email features

See user guide to read about {site-version-url}/user-manual.html#email-usage[the many other features]. 

=== Send SMS

[NOTE]
====
The samples are available in the {standard-samples-url}[sample-standard-usage sub-project].

All samples shown bellow are using SMPP for sending SMS. 
The https://en.wikipedia.org/wiki/Short_Message_Peer-to-Peer[SMPP] protocol 
is the standard way to send SMS. Only a subset of SMPP properties are used 
in following samples. The whole list of SMPP properties is available 
in {site-version-url}/user-manual.html#advanced-smpp-configuration[advanced configuration].

See {site-version-url}/user-manual.html#ovh[Sending SMS through OVH] to know how to send SMS using OVH HTTP API.
====

==== First SMS using an existing SMPP server

include::{user-manual-dir}/sms/first-sms.adoc[leveloffset=+3]

==== Use a template for SMS content

include::{user-manual-dir}/sms/template-content.adoc[leveloffset=+3]

==== Send a long SMS

include::{user-manual-dir}/sms/long-sms.adoc[leveloffset=+3]

==== Other SMS features

Ogham provides {site-version-url}/user-manual.html#sms-usage[many other features]. 


== Testing

=== Include test utilities

include::{user-manual-dir}/testing/install.adoc[leveloffset=+2]

[TIP]
====
You can 
{site-version-url}/user-manual.html#testing-tools-eclipse-static-imports[configure Eclipse]
to provide autocompletion for static imports.
====

=== Testing emails

include::{user-manual-dir}/testing/email-assertions.adoc[leveloffset=+1]


=== Testing SMS

include::{user-manual-dir}/testing/sms-assertions.adoc[leveloffset=+1]


=== More testing features

Ogham provides many other tool features:

* {site-version-url}/user-manual.html#testing-email[Email assertions and tools].
* {site-version-url}/user-manual.html#testing-sms[SMS assertions and tools].
* {site-version-url}/user-manual.html#random-ports[Use random ports to parallelize tests].


== Advanced configuration

{site-version-url}/user-manual.html#section-advanced-configuration[See advanced configuration in full documentation]

== Extend

{site-version-url}/user-manual.html#section-extend[See how to extend in full documentation]

== Tips

{site-version-url}/user-manual.html#section-tips[See tips in full documentation]

