:relative-path: ./
include::{docdir}/variables.adoc[]

:toclevels: 2
:sectnums:
:sectnumlevels: 4


= Ogham
{ogham-version}



= Existing libraries

Several libraries for sending email already exist: 

* https://commons.apache.org/proper/commons-email/[Apache Commons Email]
* https://github.com/bbottema/simple-java-mail[Simple Java Mail/Vesijama]
* http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mail.html[Spring Email Integration]
* ... 

These libraries help you send an email but if you want to use a templated content, you will have to manually integrate a template engine.

These libraries also provide only implementations based on Java Mail API. But in some environments, you might NOT want to send the email directly but to use a web service to do it for you (https://sendgrid.com/[SendGrid] for example). Furthermore, those libraries are bound by design to frameworks or libraries that you might not want to use in your own context.

So, now you would want to find a sending library with a high level of abstraction to avoid binding issues with any template engine, design framework or sender service... Is email the only possible message type ? No, so why not sending SMS, Tweet, SNMP or anything the same way ?


= The Ogham module

This module is designed for handling any kind of message the same way. It also provides several implementations for the same message type. It selects the best implementation based on the classpath or properties for example. You can easily add your own implementation.

It also provides **templating support** and integrates natively several template engines. You can also add your own.

It is **framework and library agnostic** and provides bridges for **common frameworks integration** (Spring, JSF, ...).

When using the module to send email based on an HTML template, the templating system let you **design your HTML like a standard HTML page**. It automatically transforms the associated resources (images, css files...) to be usable in an email context (automatic inline css, embed images...). You don't need to write your HTML specifically for email.


= Usage

== Include Ogham in your project

=== Include all features

==== Maven

==== Gradle

=== Select the features you need

==== Maven

==== Gradle

== Send Email

TODO: all samples are using FreeMarker -> see ThymeLeaf section

=== Your first email using an existing SMTP server

[source, java, role="collapse-lines:1-9 irrelevant-lines:1-9"]
----
include::{standard-email-samples-sourcedir}/BasicSample.java[]
----
<1> Use the standard builder (predefined behavior)
<2> Register the custom properties
<3> Create a MessagingService instance
<4> Send an email with a subject and a simple body. The sender address is automatically set using `ogham.email.from` property


=== Send email through GMail


=== Use an HTML template for email body


=== Use an HTML template for email subject

=== A working preview of the HTML body


=== Attach files to the email



=== Sending email through SendGrid



== Send SMS

=== Your first SMS using an existing SMPP server

=== use a template for SMS content

=== Send a long SMS


=== Sending SMS through SmsGlobal

=== Sending SMS through OVH



== Properties handling

=== Externalize properties in a file

=== Use system properties

=== Use properties directly in the code

=== Properties priority



== Templating

=== FreeMarker

=== ThymeLeaf

=== Mixed


== Spring Boot


= Testing

== Use a local SMTP server in tests

== Use a local SMPP server in tests

== Assert that the email is as expected

== Assert that the SMS is as expected

 
= Advanced configuration

TODO: Builders
TODO: Configurers
TODO: implementation selection
TODO: Add custom implementation
TODO: ...


= Extend

== Create your own configurer

== Use a custom message sender

== Use your custom template engine


= Tips

TODO: codes d'erreur connus avec aide