:relative-path: ./
include::{docdir}/variables.adoc[]


[[hero]]
= Hero

[.hero]
====
[.get-started]
<<user-manual.adoc#install, Get Started>>

[.belief]
We believe that developers should focus on business code instead of wasting time on technical concerns.
====


[.benefits]
====
.Code fast
[verse, role="benefit code-fast", subs="+verbatim"]
____
Ogham is designed to get you up and running as quickly as possible, with minimal upfront configuration.
Our aim is to provide a library that keeps developers focused on business code. 
Therefore, Ogham saves you painful steps. Developers don't need to be experts in RFCs or low level protocols anymore.
Even testing of message sending are simplified with Ogham.
____


.Send everything
[verse, role="benefit send-everything", subs="+verbatim"]
____
Email, sms or whatever, Ogham provides everything to send any kind of messages.
As Ogham is natively extensible, any kind of message that is not yet supported can be added easily.
____


.Integrate with everything
[verse, role="benefit integrate-with-everything", subs="+verbatim"]
____
Ogham is designed to work with real world applications.
It integrates natively with most popular frameworks.
In real world applications, sending email, sms or whatever often need to use an external service instead of the protocols.
Ogham is designed to support several implementations for sending any kind of message.
The aim is to code once and still be able to choose the implementation/protocol to use at runtime.
____


[.features]
<<features.adoc#, See Ogham features &raquo;>>

====


---


== Usage

[.send-email]
====

[.explanations]
=====

[.title]
Send a simple email

Ogham provides a single entry point (`MessagingService`) to send any message.
To send an email, just prepare the email content using the `Email` class.
The fluent API lets you chain API calls and also helps to guide developers.

In standalone mode (without framework integration), `MessagingService` has to be instantiated.
In this sample, the predefined behavior is used. The properties are used to configure
the SMTP protocol/implementation.
=====

[.code-example]
=====

[source, java, role="collapse-lines:1-9 irrelevant-lines:1-9,13-20 no-callout"]
----
include::{standard-email-samples-sourcedir}/BasicSample.java[]
----
<1> Use the standard builder (predefined behavior)
<2> Register the custom properties
<3> Create a MessagingService instance
<4> Send an email with a subject and a simple body. The sender address is automatically set using `ogham.email.from.default-value` property
=====


[.more]
<<user-manual.adoc#email-usage, Read more about email usages &raquo;>>
====


[.send-sms]
====

[.explanations]
=====

[.title]
Send a simple SMS

As mentioned above, Ogham provides a single entrypoint. Sending SMS is exactly
the same way as for email.
 
Prepare the SMS content and recipients using the `Sms` class.

The standard protocol to send SMS is SMPP. Therefore to reach the SMPP server,
properties are adapted to provide SMPP server configuration.

=====

[.code-example]
=====

[source, java, role="collapse-lines:1-9 irrelevant-lines:1-9,12-21 no-callout"]
----
include::{standard-sms-samples-sourcedir}/BasicSample.java[]
----
<1> Configure the SMPP server host
<2> Configure the SMPP server port
<3> The SMPP system ID
<4> The SMPP password
<5> The phone number of the sender
<6> Use the standard builder (predefined behavior)
<7> Register the custom properties
<8> Create a MessagingService instance
<9> Send a SMS with a simple message. The sender phone number is automatically set using `ogham.sms.from.default-value` property
=====

[.more]
<<user-manual.adoc#sms-usage, Read more about SMS usages &raquo;>>
====



[.send-templated-email]
====

[.explanations]
=====

[.title]
Send using a template

In real world applications, messages content need to be constructed with variable parts.
That's why Ogham provides integration with several templating engines.

The only difference here is the use of `TemplateContent` instead of a string.
This indicates to Ogham that the content is a template to evaluate.

The template is located in the classpath (use of `classpath:`).
The template contains variables (`name` and `value`).
To evaluate the template, a model is needed to provide values for `name` and `value`.
In the example, the class `SimpleBean` is defined with the properties and used as model.

Templates can be used for SMS or whatever in the same way.

In the sample, Thymeleaf template engine is used but it could be any template engine.
=====

[.code-example]
=====

[source, java, role="collapse-lines:1-9,34-46 irrelevant-lines:1-9,12-19 no-callout"]
----
include::{standard-email-samples-sourcedir}/HtmlTemplateSample.java[]
----
<1> Use the standard builder (predefined behavior)
<2> Register the custom properties
<3> Create a MessagingService instance
<4> Send an email with a subject and a simple body that comes from the evaluated template. The sender address is automatically set using `ogham.email.from.default-value` property
<5> Indicate the path to the HTML template file (in the classpath)
<6> Use any bean object for replacing variables in template

[source, html, role="no-callout"]
----
include::{standard-samples-resourcesdir}/template/thymeleaf/simple.html[]
----
<1> Include the ThymeLeaf namespace
<2> Use the `name` attribute value in the template
<3> Use the `value` attribute value in the template
=====

[.more]
<<user-manual.adoc#email-template, Read more about email templating &raquo;>>
<<user-manual.adoc#templating, Read more about general templating &raquo;>>
====



== Get it now


[.install-standalone]
====

[.explanations]
=====

[.title]
image:{icons-java-code} Standalone usage


`ogham-all` dependency provides all Ogham features. All implementations/protocols 
are included for all kind of messages. All supported templated engines are also included.

The aim is to start quickly and avoid wasting time on choosing dependencies.

Later, developers can adapt included features by <<user-manual.adoc#select-features-standalone, selecting Ogham dependencies>> (no need
to exclude some dependencies).
=====

[.code-example]
=====
[role=tab-container]
Include Ogham standalone dependency

[role=tab]
image:{icons-maven}

.Add `ogham-all` dependency to your pom.xml
[source, xml, subs=attributes+]
----
<dependency>
	<groupId>fr.sii.ogham</groupId>
	<artifactId>ogham-all</artifactId>
	<version>{ogham-version}</version>
</dependency>
----

[role=tab]
image:{icons-gradle}

.Add `ogham-all` dependency to your build.gradle
[source, groovy, subs=attributes+]
----
dependencies {
	implementation 'fr.sii.ogham:ogham-all:{ogham-version}'
}
----

[role=tab-container-end]
-
=====

====

[.more]
<<user-manual.adoc#install-standalone, Installation instructions &raquo;>>


[.install-spring-boot]
====

[.explanations]
=====

[.title]
image:{icons-spring-boot} Spring Boot starter

Ogham natively provides Spring Boot integration. `ogham-spring-boot-starter-all` is like
`ogham-all` but uses Spring Boot starters instead for implementations/template engines.

Developers can also select features by <<user-manual.adoc#select-features-spring-boot, selecting Ogham dependencies for Spring Boot>>. 
=====

[.code-example]
=====
[role=tab-container]
Include Ogham dependency for Spring Boot

[role=tab]
image:{icons-maven}

.Add `ogham-spring-boot-starter-all` dependency to your pom.xml
[source, xml, subs=attributes+]
----
<dependency>
	<groupId>fr.sii.ogham</groupId>
	<artifactId>ogham-spring-boot-starter-all</artifactId>
	<version>{ogham-version}</version>
</dependency>
----


[role=tab]
image:{icons-gradle}

.Add `ogham-spring-boot-starter-all` dependency to your build.gradle
[source, groovy, subs=attributes+]
----
dependencies {
	implementation 'fr.sii.ogham:ogham-spring-boot-starter-all:{ogham-version}'
}
----

[role=tab-container-end]
-
=====

====

[.more]
<<user-manual.adoc#install-spring-boot, Installation instructions &raquo;>>

