:relative-path: ../
include::{docdir}/variables.adoc[]

[[automatic-configuration]]
== Automatic configuration

Ogham automatically adapts according to the presence or not of some classes
in the classpath and values of some configuration properties. To do so, there 
are several concepts that have each a specific role and that interact together.

=== Concepts

include::{user-manual-dir}/configuration/concepts.adoc[leveloffset=+2]

=== Auto-configuration lifecycle and configuration phases

include::{user-manual-dir}/configuration/lifecycle.adoc[leveloffset=+2]


[[mimetype-detection]]
== Automatic MimeType detection

include::{user-manual-dir}/mimetype/mimetype-detection.adoc[leveloffset=+1]


[[service-providers]]
== Automatic configuration for well-known service providers

include::{user-manual-dir}/service-providers/predefined-service-providers.adoc[leveloffset=+1]




[role=TODO]
====
* List all error codes with the explanation and how to fix it (dedicated appendix ?)
  * Example: Gmail throws `javax.mail.AuthenticationFailedException`: 534-5.7.14
* Add all configuration properties (dedicated appendix ?), their default values, their effect and a description
* Add all Spring Boot properties supported by Ogham, support conditions and their effect
====