:relative-path: ../../
include::{doc-base-dir}/variables.adoc[]

== Features

- [APIs for multi-implementation support](config/select-implementation.html)
- [APIs for multi-channel support](usage/index.html)
- [Send emails using Java Mail API (first implementation)](config/select-implementation.html#email)
- [Send SMS using Cloudhopper SMPP (first implementation)](config/select-implementation.html#sms)
- Integrate Thymeleaf as template engine (first integration)
- [Manage both html and text emails](usage/how-to-send-email.html#both-html-and-text)
- [Automatically fill email/sms with information from properties](config/properties.html)
- [Automatically fill subject for emails provided directly in template](usage/how-to-send-email.html#sending-email-with-subject-from-template)
- [Handle email attachments](usage/how-to-send-email.html#attachments)
- [Apply basic HTML transformations to make the email work on several email clients](features/hidden-complexity.html)
- Detect mimetype automatically
- Simple lookup management for finding templates and template resources