:relative-path: ../../
include::{docdir}/variables.adoc[]


To test your application emails, you can start a local SMTP server. You can then use Ogham to make 
assertions on your email (right recipients, right sender, right body...). Ogham uses 
http://www.icegreen.com/greenmail/[GreenMail] as local SMTP server.

[role="tab-container no-max-height"]
====
.image:{icons-java-code} Java
[role=tab]
--

[source, java, role="collapse-lines:1-23 irrelevant-lines:1-23"]
----
include::{standard-samples-testsourcedir}/fr/sii/ogham/sample/test/EmailTestSample.java[]
----
<1> Declare and initialize the GreenMail JUnit rule to start a local SMTP server
<2> Get the local SMTP server host address and configure Ogham to use this value
<3> Get the local SMTP server port and configure Ogham to use this value
<4> Entry point for declaring assertion on received emails using a fluent API
<5> Assert that one and only one email has been received
<6> Access the first received message for declaring assertions for that message using fluent API
<7> Assert that the subject of the first message is exactly `Simple` string
<8> Assert that the sender email address is exactly `test.sender@sii.fr`
<9> Assert that the sender name is exactly `Sender Name`
<10> Assert that the recipient email address is exactly `recipient@sii.fr`
<11> Assert that the recipient name is exactly `Recipient Name`
<12> Assert that the body of the received email is exactly `string body`
<13> Assert that the mimetype of the body of the received email starts with `text/plain`
<14> Assert that received email has no alternative content
<15> Assert that received email has no attachment


{standard-samples-testsourcedir-url}/fr/sii/ogham/sample/test/EmailTestSample.java?ts={tabsize}[Source code of the sample].

--
====