:relative-path: ../../
include::{docdir}/variables.adoc[]

Ogham provides `RandomPortGreenMailRule` that simply extends `GreenMailRule`
to start on a random port instead of a fixed port.

.Random SMTP port using GreenMail
[role="tab-container no-max-height"]
====
.image:{icons-java-code} Java
[role=tab]
--

[source, java, role="collapse-lines:1-23 irrelevant-lines:1-23, highlight-lines:28,36,37"]
----
include::{standard-samples-testsourcedir}/fr/sii/ogham/sample/test/RandomPortEmailTestSample.java[]
----
<1> Declare and initialize the GreenMail JUnit rule to start a local SMTP server on a
random port
<2> Get the local SMTP server host address and configure Ogham to use this value
<3> Get the local SMTP server port and configure Ogham to use this value
<4> Entry point for declaring assertion on received emails using a fluent API
<5> Assert that one and only one email has been received
<6> Access the first received message for declaring assertions for that message using fluent API
<7> Assert that the subject of the first message is exactly `Simple` string
<8> Assert that the sender email address is exactly `test.sender@sii.fr`
<9> Assert that the sender name is exactly `Sender Name`
<10> Assert that the recipient email address is exactly `recipient@sii.fr`
<11> Assert that the recipient name is exactly `Recipient Name`
<12> Assert that the body of the received email is exactly `string body`
<13> Assert that the mimetype of the body of the received email starts with `text/plain`
<14> Assert that received email has no alternative content
<15> Assert that received email has no attachment


{standard-samples-testsourcedir-url}/fr/sii/ogham/sample/test/RandomPortEmailTestSample.java?ts={tabsize}[Source code of the sample].

--
====

For SMS testing, you don't have to change anything, it uses random port by default.
