:relative-path: ../../
include::{doc-base-dir}/variables.adoc[]

Ogham provides `RandomPortGreenMailRule` that simply extends `GreenMailRule`
to start on a random port instead of a fixed port.

.Random SMTP port using GreenMail
[role="tab-container no-max-height"]
====
.image:{icons-java-code} Java
[role=tab]
--

[source, java, role="collapse-lines:1-19 irrelevant-lines:1-19, highlight-lines:20,25,30,31"]
----
include::{standard-samples-testsourcedir}/fr/sii/ogham/sample/test/RandomPortEmailTestSample.java[]
----
<1> Declare and initialize the GreenMail JUnit extension to start a local SMTP server on a
random port
<2> Use JUnit 5 parameter injection to get GreenMail server instance
<3> Get the local SMTP server host address and configure Ogham to use this value
<4> Get the local SMTP server port and configure Ogham to use this value
<5> Use JUnit 5 parameter injection to get GreenMail server instance
<6> Entry point for declaring assertion on received emails using a fluent API
<7> Assert that one and only one email has been received
<8> Access the first received message for declaring assertions for that message using fluent API
<9> Assert that the subject of the first message is exactly `Simple` string
<10> Assert that the sender email address is exactly `test.sender@sii.fr`
<11> Assert that the sender name is exactly `Sender Name`
<12> Assert that the recipient email address is exactly `recipient@sii.fr`
<13> Assert that the recipient name is exactly `Recipient Name`
<14> Assert that the body of the received email is exactly `string body`
<15> Assert that the mimetype of the body of the received email starts with `text/plain`
<16> Assert that received email has no alternative content
<17> Assert that received email has no attachment


{standard-samples-testsourcedir-url}/fr/sii/ogham/sample/test/RandomPortEmailTestSample.java?ts={tabsize}[Source code of the sample].

--
====

For SMS testing, you don't have to change anything, it uses random port by default.
