:relative-path: ../../
include::{docdir}/variables.adoc[]


Ogham provides starters like Spring Boot does. If you are just interested in
sending emails, just include the `ogham-spring-boot-starter-email`.
It includes everything to work with email in Ogham plus FreeMarker and Thymeleaf but
it doesn't import anything to deal with SMS.

.Email with all features
[role="tab-container no-max-height"]
Select Ogham features with Spring Boot dependencies

[role=tab]
image:{icons-maven}


.pom.xml
[source, xml, subs=attributes+, role="collapse-lines:1-21,40- highlight-lines:22-26"]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.1.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>samples</groupId>
	<artifactId>ogham-and-spring-boot</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>ogham-and-spring-boot-email-only</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>11</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>fr.sii.ogham</groupId>
			<artifactId>ogham-spring-boot-starter-email</artifactId>  <!--1-->
			<version>{ogham-version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-freemarker</artifactId>   <!--2-->
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>    <!--3-->
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>         <!--4-->
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
----
<1> Add Ogham starter for Spring Boot to benefit for Ogham email features in 
your Spring Boot application.
<2> Import FreeMarker starter as usual. Ogham will adapt to additional FreeMarker 
provided by Spring Boot.
<3> Import Thymeleaf starter as usual. Ogham will adapt to additional Thymeleaf 
provided by Spring Boot.
<4> Import Mail starter as usual. Ogham will adapt to use mail features provided
by Spring Boot.


[role=tab]
image:{icons-gradle}

.build.gradle
[source, groovy, subs=attributes+, role="collapse-lines:1-13,21-27 highlight-lines:16"]
----
plugins {
	id 'org.springframework.boot' version '2.3.1.RELEASE'
	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
	id 'java'
}

group = 'samples'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'fr.sii.ogham:ogham-spring-boot-starter-email:{ogham-version}'  // <1>
	
	implementation 'org.springframework.boot:spring-boot-starter-freemarker'       // <2>
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'        // <3>
	implementation 'org.springframework.boot:spring-boot-starter-mail'             // <4>
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
}

test {
	useJUnitPlatform()
}
----
<1> Add Ogham starter for Spring Boot to benefit for email Ogham features in 
your Spring Boot application.
<2> Import FreeMarker starter as usual. Ogham will adapt to additional FreeMarker 
provided by Spring Boot.
<3> Import Thymeleaf starter as usual. Ogham will adapt to additional Thymeleaf 
provided by Spring Boot.
<4> Import Mail starter as usual. Ogham will adapt to use mail features provided
by Spring Boot.


[role=tab-container-end]
-


If you want to be even more selective, you can manually select Ogham libraries.
To benefit from Spring Boot auto-configuration, you just need to add
`ogham-spring-boot-autoconfigure`.

.Email and FreeMarker only using Spring Boot features
[role="tab-container no-max-height"]
Select Ogham features with Spring Boot dependencies

[role=tab]
image:{icons-maven}


.pom.xml
[source, xml, subs=attributes+, role="collapse-lines:1-21,47- highlight-lines:22-36"]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.1.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>samples</groupId>
	<artifactId>ogham-and-spring-boot</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>ogham-and-spring-boot-email-only</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>11</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>fr.sii.ogham</groupId>
			<artifactId>ogham-spring-boot-autoconfigure</artifactId>    <!--1-->
			<version>{ogham-version}</version>
		</dependency>
		<dependency>
			<groupId>fr.sii.ogham</groupId>
			<artifactId>ogham-email-javamail</artifactId>               <!--2-->
			<version>{ogham-version}</version>
		</dependency>
		<dependency>
			<groupId>fr.sii.ogham</groupId>
			<artifactId>ogham-template-freemarker</artifactId>          <!--3-->
			<version>{ogham-version}</version>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-freemarker</artifactId>     <!--4-->
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>           <!--5-->
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
----
<1> Provides auto-configuration to register Ogham beans in Spring Boot application. 
Also configures Ogham to use Spring Boot beans.
<2> Provides Ogham features to send emails through SMTP (using Jakarta Mail).
<3> Provides Ogham features to handle FreeMarker template engine.
<4> Import Spring Boot FreeMarker starter as usual. Ogham will automatically adapt
itself to use Spring Boot features.
<5> Import Spring Boot Mail starter. Ogham will automatically adapt
itself to use Spring Boot features.

[role=tab]
image:{icons-gradle}

.build.gradle
[source, groovy, subs=attributes+, role="collapse-lines:1-13,22-28 highlight-lines:16-18"]
----
plugins {
	id 'org.springframework.boot' version '2.3.1.RELEASE'
	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
	id 'java'
}

group = 'samples'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'fr.sii.ogham:ogham-spring-boot-autoconfigure:{ogham-version}'   // <1>
	implementation 'fr.sii.ogham:ogham-email-javamail:{ogham-version}'              // <2>
	implementation 'fr.sii.ogham:ogham-template-freemarker:{ogham-version}'         // <3>

	implementation 'org.springframework.boot:spring-boot-starter-freemarker'        // <4>
	implementation 'org.springframework.boot:spring-boot-starter-mail'              // <5>
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
}

test {
	useJUnitPlatform()
}
----
<1> Provides auto-configuration to register Ogham beans in Spring Boot application. 
Also configures Ogham to use Spring Boot beans.
<2> Provides Ogham features to send emails through SMTP (using Jakarta Mail).
<3> Provides Ogham features to handle FreeMarker template engine.
<4> Import Spring Boot FreeMarker starter as usual. Ogham will automatically adapt
itself to use Spring Boot features.
<5> Import Spring Boot Mail starter. Ogham will automatically adapt
itself to use Spring Boot features.


[role=tab-container-end]
-

