package fr.sii.ogham.testing.assertion.hamcrest;

import org.hamcrest.Description;

/**
 * Hamcrest builds description in a fixed order:
 * 
 * <pre>
 * reason text
 * Expected: a string containing "foo"
 *      but: was "bar"
 * </pre>
 * 
 * In some cases, it can be useful to totally be able to control the whole
 * description.
 * 
 * @author Aurélien Baudet
 *
 * @param <T>
 *            the type of the actual value
 */
public interface CustomDescriptionProvider<T> {
	/**
	 * Generate a new description instead of the default one.
	 * 
	 * @param reason
	 *            the reason provided in the test
	 * @param actual
	 *            the value in the test
	 * @param additionalText
	 *            additional text that can be generated by a
	 *            {@link ComparisonAwareMatcher} for example
	 * @return the description to use
	 */
	Description describe(String reason, T actual, String additionalText);
}
