:relative-path: ../../
include::{docdir}/variables.adoc[]

You may need to keep the session opened in order to avoid opening and closing session too often.
This may be necessary in situation where you send many SMS over the time.

To keep the session alive, Ogham will actively send `enquire_link` requests to the server to indicate that
the client is still alive and ready to send SMS.

To enable keep alive strategy, just update the configuration:

.Enable keep alive
[role="tab-container no-max-height"]
====
.image:{icons-java-code} Java
[role=tab]
--

[source, java, role="collapse-lines:1-9 irrelevant-lines:1-9"]
----
include::{standard-sms-samples-sourcedir}/BasicSampleExternalProperties.java[]
----
<1> Load properties from a file that is in the classpath.

{standard-sms-samples-sourcedir-url}/BasicSampleExternalProperties.java?ts={tabsize}[Source code of the sample].

--
.image:{icons-properties-file} Properties
[role=tab]
--

[source, python, role="irrelevant-lines:1-5 highlight-lines:6"]
----
include::{standard-samples-resourcesdir}/sms.properties[]
ogham.sms.cloudhopper.session.keep-alive.enable=true           # <1>
----
<1> Enable active keep alive (with default values)


--
====


The following diagram explains how it works:


.How keep alive works
[plantuml, subs="attributes", role="text-center"]
....
skinparam ParticipantPadding 40

participant Application
participant Ogham
participant EnquireLinkTask
participant Server

autonumber

Application -> Ogham: send("sms 1")
activate Ogham
Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>bind</color>
Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>bound ["session 1"]</color>
Ogham -> EnquireLinkTask: start()
activate EnquireLinkTask


Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>submit_sm ["sms 1"]</color>
Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>submit_sm_resp</color>
Application <-- Ogham: return
deactivate Ogham
|||
Application -> Ogham: send("sms 2")
activate Ogham
Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>submit_sm ["sms 2"]</color>
Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>submit_sm_resp</color>
Application <-- Ogham: return
deactivate Ogham
|||
...1 minute later...
EnquireLinkTask -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>enquire_link</color>
EnquireLinkTask <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>enquire_link_resp</color>
...1 minute later...
EnquireLinkTask -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>enquire_link</color>
EnquireLinkTask <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>enquire_link_resp</color>
...
== Repetition ==
autonumber 40
...
EnquireLinkTask -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>enquire_link</color>
EnquireLinkTask <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>enquire_link_resp</color>
...
|||
Application -> Ogham: send("sms 3")
activate Ogham
Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>submit_sm ["sms 3"]</color>
Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>submit_sm_resp</color>
Application <-- Ogham: return
deactivate Ogham
|||
...
EnquireLinkTask -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>enquire_link</color>
EnquireLinkTask <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>enquire_link_resp</color>
...1 minute later...
EnquireLinkTask -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>enquire_link</color>
EnquireLinkTask <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>enquire_link_resp</color>
...
== Repetition ==
autonumber 100
...
EnquireLinkTask -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>enquire_link</color>
EnquireLinkTask <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>enquire_link_resp</color>
...
....


By default, Ogham will send `enquire_link` requests every 30 seconds (recommended value).
The `enquire_link` requests will start *after* the first message is sent.
If the server doesn't send a response after a delay (10 seconds by default) 3 times in a row, Ogham 
will consider the connection as down.

Every value is configurable to adapt to the remote server:


.Custom keep alive configuration
[role="tab-container no-max-height"]
====
.image:{icons-java-code} Java
[role=tab]
--

[source, java, role="collapse-lines:1-9 irrelevant-lines:1-9"]
----
include::{standard-sms-samples-sourcedir}/BasicSampleExternalProperties.java[]
----
<1> Load properties from a file that is in the classpath.

{standard-sms-samples-sourcedir-url}/BasicSampleExternalProperties.java?ts={tabsize}[Source code of the sample].

--
.image:{icons-properties-file} Properties
[role=tab]
--

[source, python, role="irrelevant-lines:1-5 highlight-lines:7-10"]
----
include::{standard-samples-resourcesdir}/sms.properties[]
ogham.sms.cloudhopper.session.keep-alive.enable=true
ogham.sms.cloudhopper.session.keep-alive.connect-at-startup=true        # <1>
ogham.sms.cloudhopper.session.keep-alive.enquire-link-interval=60000    # <2>
ogham.sms.cloudhopper.session.keep-alive.enquire-link-timeout=5000      # <3>
ogham.sms.cloudhopper.session.keep-alive.max-consecutive-timeouts=5     # <4>
----
<1> Directly start sending `enquire_link` requests to keep session alive when Ogham starts
instead of waiting for first message.
<2> Change default interval between `enquire_link` requests to 1 minute.
<3> Change default response timeout to 5 seconds.
<4> Change default number of consecutive `enquire_link` requests that end in timeout to 5.


--
====


.Connection lost
[NOTE]
====
There are many cases where the connection to the server may be lost:

* The `enquire_link` request received no answer within the configured timeout
* The server has been shutdown
* The server has been restarted
* The network is not available
* ...

Ogham will detect that the session is outdated and that a new one is required. It will
try to reconnect in background. If it succeeds, `enquire_link` requests will be sent again to
actively maintain the new session. However, if it fails instead of trying to reconnect for nothing
(the server may be shutdown for a long time), it doesn't try to reconnect now. The reconnection
attempt will be done when next message is about to be sent.

Moreover, reconnection process uses the same retry strategy as connection (10 attempts
every 5 seconds by default).
====


