:relative-path: ../../
include::{docdir}/variables.adoc[]


This sample shows how to send a basic email through GMail. Sending through GMail is simply using username/password authentication and enabling SSL.

[role=tab-container no-max-height]
GMail SSL sample

[role=tab]
image:{icons-java-code} Java

[source, java, role="collapse-lines:-7 irrelevant-lines:-7 highlight-lines:16-22"]
----
include::{standard-email-samples-sourcedir}/gmail/GmailSSLBasicSample.java[]
----
<1> Use the standard builder to configure and instantiate the MessagingService as usual
<2> Use the fluent API to provide configuration properties (this is exactly the same as providing `java.util.Properties` object)
<3> GMail requires authentication so property `mail.smtp.auth` must be set to true (this is the standard JavaMail behavior)
<4> GMail SMTP host (using JavaMail standard property)
<5> GMail SMTP port (using JavaMail standard property)
<6> GMail uses SSL (JavaMail requires this special property to enable SSL)
<7> Provide your GMail username
<8> Provide your Gmail password
<9> Provide your GMail email address
<10> Send the email

{standard-email-samples-sourcedir-url}/gmail/GmailSSLBasicSample.java?ts={tabsize}[Source code of the sample]

[role=tab-container-end]
-


Using GMail server is quite easy. This samples shows several things:

1. The code to send email is still the same.
2. The properties can be provided in a fluent way.
3. SSL is enabled using standard JavaMail property.
4. Authentication is done using properties. JavaMail doesn't provide this shortcut. Without Ogham, you have to implement an http://docs.oracle.com/javaee/7/api/javax/mail/Authenticator.html[Authenticator].


[role=TODO]
====
* Explain that GMail now doesn't allow to use account password. It requires an application
password
* Show how to create application password (or just link to guide or documentation)
* Show sample with port 587
====

