:relative-path: ../../
include::{docdir}/variables.adoc[]


This sample is a variant of the previous one. It allows you to 
directly use the HTML title as subject of your email. It may be 
useful to use variables in the subject too, to mutualize the code 
and to avoid to create a new file or to use
a different evaluation syntax or context just for one line.

[role="tab-container no-max-height"]
Sample with template

[role=tab]
image:{icons-java-code} Java

[source, java, role="collapse-lines:1-10,35-47 irrelevant-lines:1-10,12-19"]
----
include::{standard-email-samples-sourcedir}/HtmlTemplateWithSubjectSample.java[]
----
<1> Subject is no more in Java code

{standard-email-samples-sourcedir-url}/HtmlTemplateWithSubjectSample.java?ts={tabsize}[Source code of the sample]

[role=tab]
image:{icons-thymeleaf} ThymeLeaf template

[source, html, role="highlight-lines:4"]
----
include::{standard-samples-resourcesdir}/template/thymeleaf/simpleWithSubject.html[]
----
<1> The subject is defined in the template and can use same evaluation context (`SimpleBean`).


NOTE: The subject of the email will be `Subject of the email - Welcome foo !`

{standard-samples-resourcesdir-url}/template/thymeleaf/simpleWithSubject.html?ts={tabsize}[Source code of the HTML template]

[role=tab-container-end]
-

