:relative-path: ../../
include::{docdir}/variables.adoc[]


This sample shows how to send an email with a content following a template engine language.

[role="tab-container no-max-height"]
Sample with template

[role=tab]
image:{icons-java-code} Java

[source, java, role="collapse-lines:1-9,34-46 irrelevant-lines:1-9,12-19 highlight-lines:28-29"]
----
include::{standard-email-samples-sourcedir}/HtmlTemplateSample.java[]
----
<1> Use the standard builder (predefined behavior)
<2> Register the custom properties
<3> Create a MessagingService instance
<4> Send an email with an explicit subject. The sender address is automatically set using `ogham.email.from.default-value` property
<5> Indicate the path to the HTML template file (in the classpath)
<6> Use any bean object for replacing variables in template

{standard-email-samples-sourcedir-url}/HtmlTemplateSample.java?ts={tabsize}[Source code of the sample].

[role=tab]
image:{icons-thymeleaf} ThymeLeaf template

[source, html]
----
include::{standard-samples-resourcesdir}/template/thymeleaf/simple.html[]
----
<1> Include the ThymeLeaf namespace
<2> Use the `name` attribute value in the template
<3> Use the `value` attribute value in the template

{standard-samples-resourcesdir-url}/template/thymeleaf/simple.html?ts={tabsize}[Source code of the HTML template]

[role=tab-container-end]
-


Using a template is straightforward. Instead of providing a string as body (using `body().string(...)`), 
you change to `body().template(..., ...)`.
The `template` method requires two pieces of information:

* The path to the template
* The variables to evaluate in the template

The path to the template is a string that may contain a *lookup* prefix. The lookup prefix is used to indicate 
where to search the template (from file system, from classpath or anywhere else). Here we explicitly 
ask to load the template from classpath (using prefix `classpath:`). If no lookup is defined, 
classpath is used by default. See <<user-manual.adoc#resource-resolution,Resource resolution section>> for more information.

The variables are any object you are using in your application. No need to convert your object to a 
particular format. Directly use what you want.