:relative-path: ../../
include::{docdir}/variables.adoc[]


Sending an email with HTML content **and** text content might be really important, at least for 
smartphones. When a smartphone receives an email, it displays the sender, the subject and also a 
preview of the message, using the text alternative. If the message is only HTML, the preview might 
be unreadable.


[role="tab-container no-max-height"]
Sample using HTML and text

[role=tab]
image:{icons-java-code} Java

[source, java, role="collapse-lines:1-9 irrelevant-lines:1-9,11-20,23-30 highlight-lines:39-40"]
----
include::{standard-email-samples-sourcedir}/HtmlAndTextSample.java[]
----
<1> Explicitly set the textual content (used as alternative body). The alternative body is used when 
the email client doesn't support HTML or as a preview of the email.
<2> Explicitly set the HTML content (used as main body)

[NOTE]
====
The call order between `text()` and `html()` doesn't matter (unlike using `.content(new MultiContent(...))`).
====

[NOTE]
====
The underlying `Content` is a `MultiContent`.
====

{standard-email-samples-sourcedir-url}/HtmlAndTextSample.java?ts={tabsize}[Source code of the sample]

[role=tab-container-end]
-



Obviously, you can use templates too. Even better, the following sample shows the shorthand version 
that avoids specifying twice the path to the templates (a single path without extension for both HTML 
and text template files).

[role="tab-container no-max-height"]
Sample using HTML and text templates

[role=tab]
image:{icons-java-code} Java

[source, java, role="collapse-lines:1-9,37-49 irrelevant-lines:1-9,12-19 highlight-lines:31-32"]
----
include::{standard-email-samples-sourcedir}/HtmlAndTextTemplateSample.java[]
----
<1> The body contains two parts (main body and alternative body) because there are two templates (one 
for HTML located at `/template/thymeleaf/simple.html` and one for text located at 
`/template/thymeleaf/simple.txt`). Only a single path is specified for both template files (without 
extension).
<2> The object used for evaluation as usual when using templates (same object used for both HTML and text)

[NOTE]
====
The underlying `Content` is a `MultiTemplateContent`.
====

{standard-email-samples-sourcedir-url}/HtmlAndTextTemplateSample.java?ts={tabsize}[Source code of the sample]

[role=tab]
image:{icons-thymeleaf-text-template} Text template

.Text template located in `src/main/resources/template/thymeleaf/simple.txt`
[source, txt]
----
include::{standard-samples-resourcesdir}/template/thymeleaf/simple.txt[]
----

{standard-samples-resourcesdir-url}/template/thymeleaf/simple.txt?ts={tabsize}[Source code of the text template]


[role=tab]
image:{icons-thymeleaf-html-template} HTML template

.HTML template located at `src/main/resources/template/thymeleaf/simple.html`
[source, html]
----
include::{standard-samples-resourcesdir}/template/thymeleaf/simple.html[]
----

{standard-samples-resourcesdir-url}/template/thymeleaf/simple.html?ts={tabsize}[Source code of the HTML template]

[role=tab-container-end]
-

Ogham will automatically determine file extensions to append according to the kind of message you 
are sending. For email, Ogham will search a HTML and a text file by default:

* Using ThymeLeaf, the file extensions are `.html` and `.txt` (configurable).
* Using FreeMarker, Ogham will search files with extensions `.html.ftl` and `.txt.ftl` (configurable).


If you are using `body()` (or explicitly using `content(new MultiTemplateContent(...))`) and you only 
provide one template (only `HTML` for example). Ogham will not fail by default (configurable). 
Therefore, you can start your code with only a HTML template and add the text template later when you 
need it. That way, your Java code doesn't require any change.



It is possible to mix templates in the same application. Even better, you can use a template engine 
that is better suited for HTML like Thymeleaf and FreeMarker that is better for textual version for 
the same email. Just write your templates with the engine you want.


[role="tab-container no-max-height"]
Sample using HTML with ThymeLeaf and text with FreeMarker

[role=tab]
image:{icons-java-code} Java

[source, java, role="collapse-lines:1-9,37-49 irrelevant-lines:1-9,12-19 highlight-lines:31-32"]
----
include::{standard-email-samples-sourcedir}/HtmlAndTextMixedTemplateEnginesSample.java[]
----
<1> The body contains two parts (main body and alternative body) because there are two templates (one 
for HTML located at `/template/thymeleaf/simple.html` and one for text located at 
`/template/thymeleaf/simple.txt.ftl`). Only a single path is specified for both template files (without 
extension). The HTML template uses Thymeleaf while the text template uses FreeMarker.
<2> The object used for evaluation as usual when using templates (same object used for both HTML and text)

{standard-email-samples-sourcedir-url}/HtmlAndTextMixedTemplateEnginesSample.java?ts={tabsize}[Source code of the sample]

[role=tab]
image:{icons-freemarker-text-template} Text template

.Text template located in `src/main/resources/template/mixed/simple.txt.ftl`
[source, txt]
----
include::{standard-samples-resourcesdir}/template/mixed/simple.txt.ftl[]
----

{standard-samples-resourcesdir-url}/template/mixed/simple.txt.ftl?ts={tabsize}[Source code of the text template]


[role=tab]
image:{icons-thymeleaf} HTML template

.HTML template located at `src/main/resources/template/mixed/simple.html`
[source, html]
----
include::{standard-samples-resourcesdir}/template/mixed/simple.html[]
----

{standard-samples-resourcesdir-url}/template/mixed/simple.html?ts={tabsize}[Source code of the HTML template]

[role=tab-container-end]
-

You can notice that the Java code has not changed at all (only the path for the sample). The aim is 
to use the template engine that best suits your needs.