:relative-path: ../../
include::{doc-base-dir}/variables.adoc[]


It retries several times with a fixed interval until the maximum attempts is reached.
It doesn't wait for the end of the previous execution.

.How it works
[role="tab-container no-max-height"]
====
.Message sent
[role=tab]
--

This diagram shows what happens if the message can't be sent twice but can be sent the third time.
The interval is configured to 5 seconds.

For the explanation, the server returns a response after 3 seconds (timeout).


[plantuml, subs="attributes", role="text-center"]
....
!pragma teoz true

skinparam ParticipantPadding 120

participant Application
participant Ogham
participant Server

autonumber

{a} Application -> Ogham: send(message)
activate Ogham
Ogham -> Ogham: execute()
activate Ogham
{b} Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>send</color>
|||
|||
{c} Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>failed</color>
deactivate Ogham
...
...
autonumber stop
{d} Application <-[#fff]- Ogham
autonumber resume
Ogham -> Ogham: execute()
activate Ogham
{e} Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>send</color>
|||
|||
{f} Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>failed</color>
deactivate Ogham
...
...
autonumber stop
{g} Application <-[#fff]- Ogham
autonumber resume
Ogham -> Ogham: execute()
Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>send</color>
Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>success</color>
Application <-- Ogham: return
deactivate Ogham


{b} <-> {c}: server timeout (3s)
{a} <-> {d}: wait for 5s\nbefore retrying
{e} <-> {f}: server timeout (3s)
{d} <-> {g}: wait for 5s\nbefore retrying
....

--
.Message can't be sent
[role=tab]
--

This diagram shows what happens if the message can't be sent and the maximum attempts 
is reached. The delay is configured to 5 seconds. The maximum attempts is configured to 4.

For the explanation, the server returns a response after 10 seconds (timeout).

[plantuml, subs="attributes", role="text-center"]
....
!pragma teoz true

skinparam ParticipantPadding 120

participant Application
participant Ogham
participant Server

autonumber

{a} Application -> Ogham: send(message)
activate Ogham
Ogham -> Ogham: execute()
activate Ogham
{b} Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>send</color>
|||
|||
{c} Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>failed</color>
deactivate Ogham
...
...
autonumber stop
{d} Application <-[#fff]- Ogham
autonumber resume

Ogham -> Ogham: execute()
activate Ogham
{e} Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>send</color>
|||
|||
{f} Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>failed</color>
deactivate Ogham
...
...
autonumber stop
{g} Application <-[#fff]- Ogham
autonumber resume

Ogham -> Ogham: execute()
activate Ogham
{h} Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>send</color>
|||
|||
{i} Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>failed</color>
deactivate Ogham
...
...
autonumber stop
{j} Application <-[#fff]- Ogham
autonumber resume

Ogham -> Ogham: execute()
activate Ogham
{k} Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>send</color>
|||
|||
{l} Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>failed</color>
deactivate Ogham

Application <-- Ogham: throw **MaximumAttemptsReachedException**
deactivate Ogham

{b} <-> {c}: server timeout (3s)
{a} <-> {d}: wait for 5s\nbefore retrying
{e} <-> {f}: server timeout (3s)
{d} <-> {g}: wait for 5s\nbefore retrying
{h} <-> {i}: server timeout (3s)
{g} <-> {j}: wait for 5s\nbefore retrying
{k} <-> {l}: server timeout (3s)
....


--
.Small interval
[role=tab]
--

This diagram shows what happens if the message can't be sent and the execution takes longer than
the configured interval. The delay is configured to 4 seconds. The maximum attempts is configured to 4.

For the explanation, the server returns a response after 10 seconds (timeout).

[IMPORTANT]
=====
The following diagram is theoretical. It totally depends on 
<<user-manual.doc#retry-executor, RetryExecutor implementation>>. The strategy just indicates
*when* the next retry *should* happen in theory.

By default, `SimpleRetryExecutor` is used and everything runs in a single thread. So it waits for 
the end of the execution even if interval is elapsed. Therefore in this particular case, the interval 
may not be respected.
=====

[plantuml, subs="attributes", role="text-center"]
....
!pragma teoz true

skinparam ParticipantPadding 60

participant Application
participant Ogham
participant Server

autonumber

{a} Application -> Ogham: send(message)
activate Ogham
Ogham -> Ogham: execute()
note left: t=0s
activate Ogham
{b} Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>send [1]</color>
note right of Ogham: first try
|||
|||
|||
|||
autonumber stop
{d} Application <-[#fff]- Ogham
autonumber resume

Ogham -> Ogham: execute()
note left: t=4s
{e} Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>send [2]</color>
note right: retrying even if first response is not received yet
|||
|||
|||
|||
autonumber stop
{g} Application <-[#fff]- Ogham
autonumber resume

Ogham -> Ogham: execute()
note left: t=8s
{h} Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>send [3]</color>
|||
|||
note right: retrying another time even if\nfirst response is not received
{c} Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>failed [1]</color>
note right: t=10s\nfirst response received
|||
|||
autonumber stop
{j} Application <-[#fff]- Ogham
autonumber resume

Ogham -> Ogham: execute()
note left: t=12s
{k} Ogham -[{plantuml-network-color}]-> Server: <color {plantuml-network-color}>send [4]</color>
note right of Ogham: retrying again
|||
|||
{f} Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>failed [2]</color>
note right: t=14s\nsecond response received
|||
|||
|||
|||
{i} Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>failed [3]</color>
note right: t=18s\nthird response received
|||
|||
|||
|||
{l} Ogham <-[{plantuml-network-color}]- Server: <color {plantuml-network-color}>failed [4]</color>
note right: t=22s\nfourth response received

Application <-- Ogham: throw **MaximumAttemptsReachedException**
deactivate Ogham

autonumber stop
Ogham -[#fff]-> Server: <color #fff>......................................................................................................................................................................</color>
autonumber resume


{b} <-> {c}: timeout [1]\n(10s)
{a} <-> {d}: wait for 4s\nbefore retrying
{e} <-> {f}: timeout [2]\n(10s)
{d} <-> {g}: wait for 4s\nbefore retrying
{h} <-> {i}: timeout [3]\n(10s)
{g} <-> {j}: wait for 4s\nbefore retrying
{k} <-> {l}: timeout [4]\n(10s)
....

--
====



.Enable re-send of email with fixed interval
[role="tab-container no-max-height"]
====
.image:{icons-java-code} Java
[role=tab]
--

[source, java, role="collapse-lines:1-9 irrelevant-lines:1-9"]
----
include::{standard-email-samples-sourcedir}/BasicClasspathPropertiesSample.java[]
----
<1> Load properties from a file that is in the classpath.

{standard-email-samples-sourcedir-url}/BasicClasspathPropertiesSample.java?ts={tabsize}[Source code of the sample].

--
.image:{icons-properties-file} Properties
[role=tab]
--

[source, python, role="irrelevant-lines:1-3 highlight-lines:4-5"]
----
include::{standard-samples-resourcesdir}/email.properties[]
ogham.email.send-retry.max-attempts=10                 # <1>
ogham.email.send-retry.delay-between-attempts=5000     # <2>
----
<1> Set the maximum attempts to `10`
<2> Set the delay (`5 seconds`) to wait for executing the next attempt after 
the execution failure


--
====


.Enable re-send of SMS with fixed interval
[role="tab-container no-max-height"]
====
.image:{icons-java-code} Java
[role=tab]
--

[source, java, role="collapse-lines:1-9 irrelevant-lines:1-9"]
----
include::{standard-sms-samples-sourcedir}/BasicSampleExternalProperties.java[]
----
<1> Load properties from a file that is in the classpath.

{standard-sms-samples-sourcedir-url}/BasicSampleExternalProperties.java?ts={tabsize}[Source code of the sample].

--
.image:{icons-properties-file} Properties
[role=tab]
--

[source, python, role="irrelevant-lines:1-5 highlight-lines:6-7"]
----
include::{standard-samples-resourcesdir}/sms.properties[]
ogham.sms.send-retry.max-attempts=10                 # <1>
ogham.sms.send-retry.delay-between-attempts=5000     # <2>
----
<1> Set the maximum attempts to `10`
<2> Set the delay (`5 seconds`) to wait for executing the next attempt after 
the execution failure


--
====
